- hosts:  all 
  become: true
  tasks:

# This is for ubuntu package 
  
  
  - name: Install apache2 package 
    apt:
      name: apache2
        - apache2
        - Add php support for apache
        - libapache2-mod-php
      state: latest
    when: ansible_architecture == "x86_64" and ansible_distribution == "Ubuntu"
 
  - name: update Respository index
    apt: 
      update_cache: yes 
      state: latest
    when: ansible_architecture == "x86_64" and ansible_distribution == "Ubuntu"



# This is for Oraclelinux package

      
  - name: Install apache2 package 
    dnf:
      name: httpd, Add php support for apache, update Respository index, libapache2-mod-php
        - httpd
        - Add php support for httpd
        - libapache2-mod-php
        - htop
      state: latest
    when: ansible_architecture == "x86_64" and ansible_distribution == "OracleLinux"
 


  - name: update Respository index
    dnf: 
      update_cache: yes 
      state: latest
    when: ansible_architecture == "x86_64" and ansible_distribution == "Ubuntu"




