

  - name: Install apache2 packages latest
    tags: apache,apach2,web_server,ubuntu
    apt:
      name:
        - apache2
        - Add php support for apache
        - libapache2-mod-php
      state: latest
    when: ansible_architecture == "x86_64" and ansible_distribution == "Ubuntu"
  

  - name: copy default hmtl file for sites  
    tags: apache,apache2,httpd 
    copy:
      src: default_site.html
      dest: /var/www/hmtl/index.html
      owner: root
      group: root 
      mode: 0644


# this Oracle
    

  - name: httpd, Add php support for apache
    dnf:
      name:
        - httpd
        - Add php support for httpd
        - libapache2-mod-php
      state: latest
    when: ansible_architecture == "x86_64" and ansible_distribution == "OracleLinux"

  - name: change mail address for admin(Oracle)
    tags: apache,httpd,rocky
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin pheemyhan@gmail.com
    when: ansible_distribution == "OracleLinux"
    register: httpd


  - name: Restart Httpd 
    tags: apache, oracle,httpd
    services:
      name: httpd
      state:  restarted
    when: httpd.changed

    

  











